export const API_URI = 'http://192.168.0.25';
//export const API_URI = 'https://www.feeeling.co.kr';
//export const API_URI = 'http://demo.radiko.co.kr/feeeling';
//export const API_URI='http://192.168.0.26:9090/feeeling';
/** user Actions[S] */
export const LOGIN = 'LOGIN';
export const SELECT_UNDER_14 = 'SELECT_UNDER_14';
export const SELECT_OVER_14 = 'SELECT_OVER_14';
export const KAKAO_LOGIN = 'KAKAO_LOGIN';
export const KAKAO_LOGIN_FAIL_SET_JOIN = 'KAKAO_LOGIN_FAIL_SET_JOIN';
export const NAVER_LOGIN = 'NAVER_LOGIN';
export const NAVER_LOGIN_FAIL_SET_JOIN = 'NAVER_LOGIN_FAIL_SET_JOIN';
export const JOIN = 'JOIN';
export const SMS_AUTH_REQUEST = 'SMS_AUTH_REQUEST';
export const SMS_AUTH_CONFIRM = 'SMS_AUTH_CONFIRM';
export const SMS_AUTH_FAIL = 'SMS_AUTH_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const SET_JOIN_PROFILE = 'SET_JOIN_PROFILE';
/** user Actions[E] */
/** common Actions[S] */
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const GET_PROFILE_IMAGE_SUCCESS = 'GET_PROFILE_IMAGE_SUCCESS';
export const GET_TESTEE_PROFILE_IMAGE_SUCCESS =
  'GET_TESTEE_PROFILE_IMAGE_SUCCESS';
export const GET_TEST_IMAGE_SUCCESS = 'GET_TEST_IMAGE_SUCCESS';
export const GET_IMAGE_FAIL = 'GET_IMAGE_FAIL';
export const SPLASH_SWITCH_ON = 'SPLASH_SWITCH_ON';
export const SPLASH_SWITCH_OFF = 'SPLASH_SWITCH_OFF';
export const SET_RESOUCE_FINISH = 'SET_RESOUCE_FINISH';
export const DONT_SPLASH_NOW = 'DONT_SPLASH_NOW';
export const DO_SPLASH_NOW = 'DO_SPLASH_NOW';
export const GET_NOTICE_LIST_SUCCESS = 'GET_NOTICE_LIST_SUCCESS';
export const GET_NOTICE_LIST_FAIL = 'GET_NOTICE_LIST_FAIL';
export const NOTICE_LIST_LOADED = 'NOTICE_LIST_LOADED';
export const NOTICE_LIST_LOADED_FINISH = 'NOTICE_LIST_LOADED_FINISH';
export const GET_ALARM_LIST_FIRST_SUCCESS = 'GET_ALARM_LIST_FIRST_SUCCESS';
export const GET_ALARM_LIST_SUCCESS = 'GET_ALARM_LIST_SUCCESS';
export const GET_ALARM_LIST_FAIL = 'GET_ALARM_LIST_FAIL';
export const ALARM_LIST_LOADED = 'ALARM_LIST_LOADED';
export const ALARM_LIST_LOADED_FINISH = 'ALARM_LIST_LOADED_FINISH';

export const GET_MESSAGE_BACKGROUND = 'GET_MESSAGE_BACKGROUND';
/** common Actions[E] */
/** main Actions[S] */
export const LIST_LOADED = 'LIST_LOADED';
export const LIST_LOADED_FINISH = 'LIST_LOADED_FINISH';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_LIST_INFO = 'GET_LIST_INFO';
export const GET_LIST_INFO_FAIL = 'GET_LIST_INFO_FAIL';
export const GET_TEST_USER_INFO = 'GET_TEST_USER_INFO';
export const SET_TESTEE_USER = 'SET_TESTEE_USER';
export const GET_TEST_LIST = 'GET_TEST_LIST';
export const CORRECTION_PICTURE = 'CORRECTION_PICTURE';
export const QUESTION_SET = 'QUESTION_SET';
export const IMAGE_TEXT_CHANGE = 'IMAGE_TEXT_CHANGE';
export const ANSWER_CHANGE = 'ANSWER_CHANGE';
export const ANSWER_SET = 'ANSWER_SET';
export const REQUEST_TEST_SUCCESS = 'REQUEST_TEST_SUCCESS';
export const REQUEST_TEST_RESET = 'REQUEST_TEST_RESET';
export const REQUEST_RESULT = 'REQUEST_RESULT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const INIT_FILTER = 'INIT_FILTER';
export const GET_TEST_TYPE = 'GET_TEST_TYPE';
export const REQUEST_RESULT_IMAGE = 'REQUEST_RESULT_IMAGE';

export const SET_CHANGE_TESTEE_TEMP = 'SET_CHANGE_TESTEE_TEMP';
/** main Actions[E] */
